#!/bin/bash

# installs afdsmgrd from cvmfs. afdsmgrd is taken from a certain ROOT version;
# specify it with:
#   ./install_afdsmgrd_from_cvmfs.sh [v1-22-33]
# if omitted, defaults to v5-34-13.

if [[ `whoami` != 'root' ]] ; then
  echo 'you must be root to install afdsmgrd'
  exit 1
fi

# default root version
rootver='v5-34-13'
[[ "$1" != '' ]] && rootver="$1"

source /cvmfs/alice.cern.ch/etc/login.sh
eval $( alienv printenv VO_ALICE@ROOT::"$rootver" )

which afdsmgrd > /dev/null 2>&1
if [[ $? != 0 ]] ; then
  echo "cannot find afdsmgrd on cvmfs: check ROOT version (using $rootver)"
  exit 1
fi

rootprefix=`which afdsmgrd`
rootprefix=`dirname "$rootprefix"`/..
rootprefix=`cd "$rootprefix" ; pwd`

initd="$rootprefix/etc/proof/init.d/afdsmgrd"

# install init.d script (i.e.: startup/shutdown script)
ln -nfs "$initd" /etc/init.d/afdsmgrd
chkconfig --add afdsmgrd

# disable autostart at boot (enable with "on" if you wish)
chkconfig afdsmgrd off

# example of startup file
#cat $rootprefix/etc/proof/sysconfig/afdsmgrd.example

# create directory for pidfile (bug in afdsmgrd)
mkdir -p '/home/vseadmin/afdsmgrd/run'
chmod +x /home/vseadmin
chmod u=rwX,g=rX,o=rX -R /home/vseadmin/afdsmgrd
chown vseadmin:vseadmin -R /home/vseadmin/afdsmgrd

# create startup file
cat > /etc/sysconfig/afdsmgrd <<_EOF_
# Automatically generated by install_afdsmgrd_from_cvmfs.sh
export AFDSMGRD_PROG="$rootprefix/bin/afdsmgrd"
export AFDSMGRD_CONF='/home/vseadmin/afdsmgrd/config/afdsmgrd.conf'
export ROOTSYS="$rootprefix"
export AFDSMGRD_LIBS="$LD_LIBRARY_PATH"
export AFDSMGRD_EXTCMD_LIBS="\$AFDSMGRD_LIBS"
export AFDSMGRD_EXTCMD_PATH="$PATH"
export AFDSMGRD_LIBEXEC="$rootprefix/etc/proof"
export AFDSMGRD_LOGDIR="/home/vseadmin/afdsmgrd/log"
export AFDSMGRD_LOGFILE="\$AFDSMGRD_LOGDIR/afdsmgrd.log"
export AFDSMGRD_PIDFILE='/home/vseadmin/afdsmgrd/run/afdsmgrd.pid'
export AFDSMGRD_USER='vseadmin'
export AFDSMGRD_GROUP='vseadmin'
export AFDSMGRD_LOGLEVEL='high'
_EOF_

# user messages
echo
echo 'afdsmgrd installed'
echo
echo 'original location:'
echo "  `which afdsmgrd`"
echo
echo "reference ROOT version (change with: \"$0 v1-22-33\"):"
echo "  $rootver"
echo
echo 'now you can control afdsmgrd by means of:'
echo '  service afdsmgrd [start|stop|status]'
echo
echo 'if you want it to start automatically at boot:'
echo '  chkconfig afdsmgrd on'
echo
